### ISSUE TITLE
publish to npm and bower

### ISSUE THREAD

**Issue by boromil** [SlashDB/angular-slashdb#1]
npm: https://docs.npmjs.com/getting-started/publishing-npm-packages
bower: https://bower.io/docs/creating-packages/

seems simple enough

**Comment by boromil** [comment]
you can now
> bower install angular-slashdb

or

> npm install angular-slashdb

to install the angular-slashdb package

also _https://www.npmjs.com/package/angular-slashdb_
the README.md file will be updated later

**Comment by agilevic** [comment]
Nice. Now we need documentation too. Also, as both packages evolve how
should one know what version of angular-slashdb to use with a given version
of slashdb?
Victor Olex
Founder and CEO
VT Enterprise / SlashDB
http://slashdb.com


Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by boromil** [comment]
that can be specified by the README - every _git tag_ has it's own version
