### ISSUE TITLE
add SlashDB Data Discovery features

### ISSUE THREAD

**Issue by mdobrzanski** [SlashDB/angular-slashdb#2]
The angular-slashdb api should support main SlashDB Data Discovery features like

Any request may be called with extension .json or header Accpet=application/json

# List available databases 
http://slashdb:6543/db.json

# List tables in database
http://slashdb:6543/db/SQLiteChinook.json

# Data drill down
GET parameters:
- http://slashdb:6543/db/SQLiteChinook/Customer/CustomerId/..2.json?**depth=1**
- http://slashdb:6543/db/SQLiteChinook/Customer.json?**limit=2**
- http://slashdb:6543/db/SQLiteChinook/Customer.json?**offset=2**
- http://slashdb:6543/db/SQLiteChinook/Customer/FirstName,LastName,Email.json?**sort=LastName**
- http://slashdb:6543/db/SQLiteChinook/Customer/LastName.json?**distinct**

# Adding objects
POST request with object to table url http://slashdb:6543/db/SQLiteChinook/Customer.json should result in adding new resource.

# Updating data
Object update using PUT request with object to object url ttp://slashdb:6543/db/SQLiteChinook/Customer/CustomerId/2.json or

Scalar update using PUT request with value to scalar url slashdb:6543/db/SQLiteChinook/Customer/CustomerId/1/LastName.json

**Comment by boromil** [comment]
> Adding objects
> Updating data

A _post_ method exists and I added a new _put_ method just a moment ago - usage is exactly the same as with _post_. I'll add a example usage to the example app later.

> List available databases
> List tables in database

That works just fine via the _get_ method, see _main.js_ in example app.

The user can now pass in an additional request config object to set ad-hoc request attributes i.e. headers, query params - this works for _get_, _post_, _put_, _executeQuery_ (SQL Pass-thru) methods of the _slashDB_ service.

```javascript
var requestConfig = {
    params: {
        limit: 50,
        sort: 'Name',
        offset: 3
     },
    headers: {
        'Accpet': 'application/json'
    }
};
slashDB.get('/db/SQLiteChinook/Customer.json', requestConfig);
```
For more on config object content see https://code.angularjs.org/1.5.7/docs/api/ng/service/$http#usage .
