### ISSUE TITLE
setup example app as github page

### ISSUE THREAD

**Issue by boromil** [SlashDB/angular-slashdb#9]

**Comment by boromil** [comment]
A preview is on [here](https://slashdb.github.io/angular-slashdb/).
All the assets from _example_ directory from _main_ branch, are copied over to _gh-pages_ branch.
GitHub looks there for an index.html file to serve.

**Comment by boromil** [comment]
Checkout [this preview](https://slashdb.github.io/angular-slashdb/).
It's small but it shows some of the features of angular-slashdb i.e. api key authentication, error handling, making request (with query params).

Comments are welcomed :)

**Comment by mdobrzanski** [comment]
Cookies with pure xhr work. Maybe it's something with angular or our code.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<script>
    var postData = {
        login: 'angular',
        password: 'angular'
    };
    var loginXhr = new XMLHttpRequest();
    loginXhr.open('POST', 'http://beta.slashdb.com/login', false);
    loginXhr.withCredentials=true;
    loginXhr.setRequestHeader("Content-type", "application/json");
    loginXhr.send(JSON.stringify(postData));

    var getXhr = new XMLHttpRequest();
    getXhr.open('GET', 'http://beta.slashdb.com/db/Chinook/Artist.json?limit=3', false);
    getXhr.withCredentials=true;
    getXhr.send(null);
    if (getXhr.status === 200){
        console.log('response data ', getXhr.responseText);
    }
</script>

</body>
</html>
```

**Comment by boromil** [comment]
has been fixed, the only issue is that we don't have a legit ssl cert but that's on beta.slashdb.com
